export { default as Footer } from './Footer';
export { default as Layout } from './Layout';
export { default as Navbar } from './Navbar';
export { default as Product } from './Product';
export { default as HeroBanner } from './HeroBanner';
export { default as FooterBanner } from './FooterBanner';
export { default as Cart } from './Cart';
export {default as SplashScreen} from './SplashScreen';
export {default as Carousel} from './Carousel';
// export {default as UserDashboard} from './UserDashboard';
// export {default as Modal} from './Modal';